<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'jayjay666\\WPRequirementsChecker\\Tests\\' => array($vendorDir . '/jayjay666/wp-requirements-checker/tests'),
    'jayjay666\\WPRequirementsChecker\\' => array($vendorDir . '/jayjay666/wp-requirements-checker/src'),
    'jayjay666\\SectionColumnBooster\\includes\\' => array($baseDir . '/includes'),
    'jayjay666\\SectionColumnBooster\\' => array($baseDir . '/src'),
);
