<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit4e226682dc515a6c82a9f9c766f166ca
{
    public static $prefixLengthsPsr4 = array (
        'j' => 
        array (
            'jayjay666\\WPRequirementsChecker\\Tests\\' => 38,
            'jayjay666\\WPRequirementsChecker\\' => 32,
            'jayjay666\\SectionColumnBooster\\includes\\' => 40,
            'jayjay666\\SectionColumnBooster\\' => 31,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'jayjay666\\WPRequirementsChecker\\Tests\\' => 
        array (
            0 => __DIR__ . '/..' . '/jayjay666/wp-requirements-checker/tests',
        ),
        'jayjay666\\WPRequirementsChecker\\' => 
        array (
            0 => __DIR__ . '/..' . '/jayjay666/wp-requirements-checker/src',
        ),
        'jayjay666\\SectionColumnBooster\\includes\\' => 
        array (
            0 => __DIR__ . '/../..' . '/includes',
        ),
        'jayjay666\\SectionColumnBooster\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit4e226682dc515a6c82a9f9c766f166ca::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit4e226682dc515a6c82a9f9c766f166ca::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit4e226682dc515a6c82a9f9c766f166ca::$classMap;

        }, null, ClassLoader::class);
    }
}
